name: Deploy to GitHub Pages

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 14.21.3
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build -- --base-href="/ng-onlyoffice/"

            - name: Deploy to GitHub Pages
              if: github.event_name == 'push'
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/ng-onlyoffice
